### ISSUE TITLE
Watch module ZNC 

### ISSUE THREAD

**Issue by NikoZion** [znc/znc#1898]
Hello,

I just added watch module on my ZNC.
When I join or leave a channel *highlight and *status open a window : [*status] No such module highlight
and in highlight I have the join or leave information.

How to disable it please ?

Thanks !

**Comment by RealKindOne** [comment]
You need to ```setsource <id> priv```.
```
[21:42:54] <KindOne> list
[21:42:54] <*watch> You have no entries.
[21:42:56] <KindOne> add * *highlight *%nick%*
[21:42:59] <KindOne> list
[21:43:00] <*watch> +----+----------+------------+----------+---------+-----+--------------------+---------------------+
[21:43:00] <*watch> | Id | HostMask | Target     | Pattern  | Sources | Off | DetachedClientOnly | DetachedChannelOnly |
[21:43:00] <*watch> +----+----------+------------+----------+---------+-----+--------------------+---------------------+
[21:43:00] <*watch> | 1  | *!*@*    | *highlight | *%nick%* |         |     | No                 | No                  |
[21:43:00] <*watch> +----+----------+------------+----------+---------+-----+--------------------+---------------------+
[21:43:03] <KindOne> setsources 1 priv
[21:43:03] <*watch> Sources set for Id 1.
[21:43:06] <KindOne> list
[21:43:06] <*watch> +----+----------+------------+----------+---------+-----+--------------------+---------------------+
[21:43:06] <*watch> | Id | HostMask | Target     | Pattern  | Sources | Off | DetachedClientOnly | DetachedChannelOnly |
[21:43:06] <*watch> +----+----------+------------+----------+---------+-----+--------------------+---------------------+
[21:43:07] <*watch> | 1  | *!*@*    | *highlight | *%nick%* | priv    |     | No                 | No                  |
[21:43:07] <*watch> +----+----------+------------+----------+---------+-----+--------------------+---------------------+

```

https://wiki.znc.in/Watch


P.S. You can try the IRC channel ```irc.libera.chat #znc``` for a possibly faster responce time.

**Comment by NikoZion** [comment]
I do :  setsources 1 private
I don't see the HL when AFK and back again.

**Comment by NikoZion** [comment]
Sorry I forgot channel but now still : 

[13:52:15] [*status] No such module highlight

**Comment by RealKindOne** [comment]
I made a mistake in the example. The ```priv``` is for private messages/ctcps.

Enter this, it should fix the issue.``` setsources 1 #*``` that will make the module work on all channels.

I only get ```<*status> No such module highlite``` when I message the module.

**Comment by NikoZion** [comment]
Still the same I join or part of a channel : 
[15:02:01] [*highlight] * ... parts ...
[15:00:01] [*status] No such module highlight
[14:59:58] [*highlight] * ... parts ... 
[15:00:01] [*status] No such module highlight

Someone HL me : 

[15:03:23] [*status] No such module highlight

**Comment by NikoZion** [comment]
[15:05:03] [X] Setsources 1 #*
[15:05:04] [*watch] Sources set for Id 1.
